spring:
  application:
    name: controller
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=jes_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 8081
auth:
  clientId: client-id
  clientSecret: $2a$10$kVuyPCSQNnrTgExnJp1O3uhFBpFDa/8PEPNMY3V15GG1LKA.4u.CC